# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-21 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190821_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='info',
            new_name='bookInfo',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='image',
            new_name='bookLog',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='bookname',
            new_name='bookName',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='state',
            new_name='bookState',
        ),
    ]
