# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-22 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190821_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontent',
            name='content',
            field=models.TextField(max_length=15000, verbose_name='内容'),
        ),
    ]
