# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-22 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20190822_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcontent',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
    ]
