# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-28 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20190822_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kin',
            field=models.CharField(default='null', max_length=100, verbose_name='属'),
        ),
    ]
