# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-28 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_kin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='kin',
            new_name='kind',
        ),
    ]
