# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-25 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookname', models.CharField(max_length=50, verbose_name='书名')),
                ('info', models.TextField(verbose_name='内容简介')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃')),
            ],
        ),
        migrations.CreateModel(
            name='BookCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_alieve', models.BooleanField(default=True, verbose_name='活跃')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Book')),
            ],
        ),
        migrations.CreateModel(
            name='BookContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=100, verbose_name='章节名')),
                ('content', models.TextField(verbose_name='内容')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='活跃')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.BookContent')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='用户密码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('join_time', models.DateField(auto_now_add=True, verbose_name='申请时间')),
                ('head_portrait', models.ImageField(null=True, upload_to='', verbose_name='头像')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('gender', models.BooleanField(default=True, verbose_name='性别')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='生日')),
                ('is_author', models.BooleanField(default=False, verbose_name='是否为作者')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='bookcontent',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='bookcase',
            name='mark',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.BookContent'),
        ),
        migrations.AddField(
            model_name='bookcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
