# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-08-07 11:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='用户名')),
                ('nickname', models.CharField(max_length=30, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('sign', models.CharField(max_length=50, null=True, verbose_name='个人签名')),
                ('info', models.CharField(max_length=150, null=True, verbose_name='个人描述')),
                ('avatar', models.ImageField(null=True, upload_to='avatar/')),
                ('birthday', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='bookcase',
            name='is_alieve',
        ),
        migrations.RemoveField(
            model_name='bookcontent',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AlterField(
            model_name='bookcase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AlterField(
            model_name='bookcontent',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
